services:
  database:
    image: postgres:18
    container_name: task-forge-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - task-forge-network
    volumes:
      - /data:/var/lib/postgresql

networks:
  task-forge-network:
    driver: bridge
